/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cold_yyh_com_myndk01_NdkJniUtils */

#ifndef _Included_cold_yyh_com_myndk01_NdkJniUtils
#define _Included_cold_yyh_com_myndk01_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cold_yyh_com_myndk01_NdkJniUtils
 * Method:    uninstallListener
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cold_yyh_com_myndk01_NdkJniUtils_uninstallListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
