/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


JNIEXPORT jstring JNICALL Java_cold_yyh_com_myndk01_NdkJniUtils_getCLanguageString (JNIEnv * env, jobject obj){
  return (*env)->NewStringUTF(env,"你好，ndk，我来了");
}
